In [42]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
import os
for dirname, _, filenames in os.walk('.'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./Delivery_truck_tri_ data.csv
./Delivery truck trip data.xlsx
./Untitled.ipynb
./.ipynb_checkpoints/Untitled-checkpoint.ipynb

In [53]:
df = pd.read_csv("./Delivery_truck_tri_ data.csv")
with pd.option_context('display.max_rows', 6, 'display.max_columns', None): 
    display(df)

,GpsProvider,BookingID,Market/Regular,BookingID_Date,vehicle_no,Origin_Location,Destination_Location,Org_lat_lon,Des_lat_lon,Data_Ping_time,Planned_ETA,Current_Location,DestinationLocation,actual_eta,Curr_lat,Curr_lon,ontime,delay,OriginLocation_Code,DestinationLocation_Code,trip_start_date,trip_end_date,TRANSPORTATION_DISTANCE_IN_KM,vehicleType,Minimum_kms_to_be_covered_in_a_day,Driver_Name,Driver_MobileNo,customerID,customerNameCode,supplierID,supplierNameCode,Material Shipped
0,CONSENT TRACK,MVCV0000927/082021,Market,8/17/2020,KA590408,"TVSLSL-PUZHAL-HUB,CHENNAI,TAMIL NADU","ASHOK LEYLAND PLANT 1- HOSUR,HOSUR,KARNATAKA","13.1550,80.1960","12.7400,77.8200",05:09.0,59:01.0,"Vaniyambadi Rd, Valayambattu, Tamil Nadu 63575...","ASHOK LEYLAND PLANT 1- HOSUR,HOSUR,KARNATAKA",8/28/2020 14:38,12.663500,78.649870,NaN,R,CHEPUZTVSHUA1,HOSHOSALLCCA2,8/17/2020 14:59,NaN,320.0,NaN,NaN,NaN,NaN,ALLEXCHE45,Ashok leyland limited,VIJEXHOSR7,VIJAY TRANSPORT,BRACKET / GRAB HANDLE
1,VAMOSYS,VCV00014271/082021,Regular,8/27/2020,TN30BC5917,"DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...","12.8390,79.9540","12.8390,79.9540",40:28.0,22:22.8,"Unnamed Road, Oragadam Industrial Corridor, Va...","DAIMLER INDIA COMMERCIAL VEHICLES,KANCHIPURAM,...",8/28/2020 12:46,12.836757,79.954428,G,NaN,CHEORADMRCCB1,CHEMATDMROPA7,8/27/2020 16:21,NaN,103.0,NaN,NaN,RAMESH,NaN,DMREXCHEUX,Daimler india commercial vehicles pvt lt,VJLEXSHE09,VJ LOGISTICS,ZB MODEL PLATE / 3143
2,CONSENT TRACK,VCV00014382/082021,Regular,8/27/2020,TN22AR2748,"LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY","11.8710,79.7390","11.8710,79.7390",05:09.0,59:25.0,"570, National Hwy 48, Shenoy Nagar, Chennai, T...","LUCAS TVS LTD-PONDY,PONDY,PONDICHERRY",8/28/2020 16:03,13.073956,80.225780,G,NaN,CHEPONLUTCCA4,CHEPONLUTCCA4,8/27/2020 17:57,NaN,300.0,NaN,NaN,GIRI,NaN,LUTGCCHE06,Lucas tvs ltd,GSTEXLAK1Q,G.S. TRANSPORT,LETTERING / FUSO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6877,JTECH,WDSBKTP43021,Regular,3/29/2019,KA01AE9163,"Mugabala, Bangalore Rural, Karnataka","Anekal, Bangalore, Karnataka","16.560192249175344,80.792293091599547","12.722686,77.676518",20:12.0,38:00.0,"Shed No 60, Medahalli Kadugodi Road, Virgonaga...","Anekal, Bangalore, Karnataka",3/30/2019 0:53,13.024788,77.722391,G,NaN,V0048673,LE005848,3/29/2019 20:44,3/30/2019 0:53,49.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,SPARE PARTS AUTOMOBILE
6878,JTECH,WDSBKTP42685,Regular,3/27/2019,KA21A3643,"Mugabala, Bangalore Rural, Karnataka","Anekal, Bangalore, Karnataka","16.560192249175344,80.792293091599547","12.896896847817695,77.712223056874862",20:12.0,20:00.0,"Shed No 60, Medahalli Kadugodi Road, Virgonaga...","Anekal, Bangalore, Karnataka",3/27/2019 16:35,13.024747,77.721823,NaN,R,V0048673,LEL04580,3/27/2019 15:29,3/27/2019 16:35,49.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,SPARE PARTS AUTOMOBILE
6879,JTECH,WDSBKTP42858,Regular,3/28/2019,KA51D1317,"Mugabala, Bangalore Rural, Karnataka","Anekal, Bangalore, Karnataka","16.560192249175344,80.792293091599547","13.199089183304451,77.708554234959038",20:12.0,26:00.0,"20/1, Sulthangunta, Shivaji Nagar, Bengaluru, ...","Anekal, Bangalore, Karnataka",3/28/2019 23:41,12.991815,77.606038,G,NaN,V0048673,LE005770,3/28/2019 20:26,3/28/2019 23:41,49.0,40 FT 3XL Trailer 35MT,NaN,NaN,NaN,LTLEXMUM40,Larsen & toubro limited,55556,A S TRANSPORTS,SPARE PARTS AUTOMOBILE

In [50]:
print("Columns:",df.columns)
isnull_count = pd.DataFrame(df.isnull().sum(), columns=["isnull count"])
isna_count = pd.DataFrame(df.isnull().sum(), columns=["isna count"])
isin_count = pd.DataFrame(df.isin(["NaN", "-", "", ".", "_", "?"]).sum(), columns=["isin count"])
pd.concat([isnull_count, isna_count, isin_count], axis=1)

Columns: Index(['GpsProvider', 'BookingID', 'Market/Regular ', 'BookingID_Date',
       'vehicle_no', 'Origin_Location', 'Destination_Location', 'Org_lat_lon',
       'Des_lat_lon', 'Data_Ping_time', 'Planned_ETA', 'Current_Location',
       'DestinationLocation', 'actual_eta', 'Curr_lat', 'Curr_lon', 'ontime',
       'delay', 'OriginLocation_Code', 'DestinationLocation_Code',
       'trip_start_date', 'trip_end_date', 'TRANSPORTATION_DISTANCE_IN_KM',
       'vehicleType', 'Minimum_kms_to_be_covered_in_a_day', 'Driver_Name',
       'Driver_MobileNo', 'customerID', 'customerNameCode', 'supplierID',
       'supplierNameCode', 'Material Shipped'],
      dtype='object')

                                    isnull count  isna count  isin count
GpsProvider                                  953         953           0
BookingID                                      0           0           0
Market/Regular                                 0           0           0
BookingID_Date                                 0           0           0
vehicle_no                                     0           0           0
Origin_Location                                0           0           0
Destination_Location                           0           0           0
Org_lat_lon                                    0           0           0
Des_lat_lon                                    0           0           0
Data_Ping_time                               953         953           0
Planned_ETA                                    0           0           0
Current_Location                             964         964           0
DestinationLocation                            0           0           0
actual_eta                                    37          37           0
Curr_lat                                     953         953           0
Curr_lon                                     953         953           0
ontime                                      4332        4332           0
delay                                       2538        2538           0
OriginLocation_Code                            3           3           0
DestinationLocation_Code                      27          27           0
trip_start_date                                0           0           0
trip_end_date                                194         194           0
TRANSPORTATION_DISTANCE_IN_KM                712         712           0
vehicleType                                  828         828           0
Minimum_kms_to_be_covered_in_a_day          4060        4060           0
Driver_Name                                 3429        3429           0
Driver_MobileNo                             4189        4189           0
customerID                                     0           0           0
customerNameCode                               0           0           0
supplierID                                     0           0           0
supplierNameCode                               0           0           0
Material Shipped                               0           0           0